global:
  release:
    version: 32.1.0
  metadata:
    name: "test"
    organization: "test"
    description: "test description"

  connectivity:
    baseDomain: example.com

  providerSpecific:
    awsAccountId: "1234567890"

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
