global:
  release:
    version: 32.1.0
  metadata:
    name: test-wc-minimal
    organization: test
    servicePriority: lowest
  connectivity:
    baseDomain: example.com
  providerSpecific:
    region: "eu-west-1"
    awsAccountId: "1234567890"

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
